# Generated by Django 3.1.3 on 2020-11-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('alias', models.CharField(max_length=50, verbose_name='alias')),
                ('imagen', models.ImageField(upload_to=None, verbose_name='imagen')),
                ('logo', models.ImageField(upload_to=None, verbose_name='logo')),
                ('superpoder', models.CharField(max_length=50, verbose_name='superpoder')),
                ('comic', models.CharField(max_length=50, verbose_name='comic')),
                ('pelicula', models.CharField(max_length=50, verbose_name='pelicula')),
                ('raza', models.CharField(max_length=50, verbose_name='raza')),
                ('estado', models.CharField(max_length=50, verbose_name='estado')),
            ],
        ),
    ]
