# Generated by Django 3.1.3 on 2020-12-07 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroe',
            options={'verbose_name': 'Heroe', 'verbose_name_plural': 'Heroes'},
        ),
        migrations.AddField(
            model_name='heroe',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Autor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heroe',
            name='imagen',
            field=models.ImageField(upload_to='Heroes', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='heroe',
            name='logo',
            field=models.ImageField(upload_to='Heroes', verbose_name='logo'),
        ),
    ]
